// File generated by FlutterFire CLI.
// THIS IS A TEMPLATE - Replace with your actual configuration
// Run: flutterfire configure --project=your-project-id

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ 以下配置需要替换为你的 Firebase 项目信息
  // 从 Firebase Console 下载配置文件后，运行 flutterfire configure 生成

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'brainfit-app',
    authDomain: 'brainfit-app.firebaseapp.com',
    storageBucket: 'brainfit-app.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK6fxJT8vRAIhcf7Ym8tX2tUsTyf0DJ6E',
    appId: '1:487600965196:android:fc417553322563716e56e9',
    messagingSenderId: '487600965196',
    projectId: 'brainfit-app',
    storageBucket: 'brainfit-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpno0NpEp86YG3YGQs-YTW9kA6MA-na4Q',
    appId: '1:487600965196:ios:9039a696a8fd9b7c6e56e9',
    messagingSenderId: '487600965196',
    projectId: 'brainfit-app',
    storageBucket: 'brainfit-app.firebasestorage.app',
    iosBundleId: 'com.brainfit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'brainfit-app',
    storageBucket: 'brainfit-app.appspot.com',
    iosBundleId: 'com.brainfit.app.macos',
  );
}

/// 开发环境配置（模拟器/测试）
class FirebaseDevOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'dev-api-key',
    appId: 'dev-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'brainfit-dev',
    storageBucket: 'brainfit-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'dev-api-key',
    appId: 'dev-app-id',
    messagingSenderId: 'dev-sender-id',
    projectId: 'brainfit-dev',
    storageBucket: 'brainfit-dev.appspot.com',
    iosBundleId: 'com.brainfit.app.dev',
  );
}
